- name: Copies {{COMPONENT}} repo file
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/default.conf
    before: '# live site config'
    regexp: '^(.+)$'
    replace: '# \1'