- name: Copies {{COMPONENT}} repo file
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: started
    name: mongod
    enabled: yes 

- name: Download and extract {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Run a js file containing MongoDB commands with pseudo-idempotency
  community.mongodb.mongodb_shell:
    file: "/tmp/{{COMPONENT}}-main/users.js"
    idempotent: yes

- name: Run a js file containing MongoDB commands with pseudo-idempotency
  community.mongodb.mongodb_shell:
    file: "/tmp/{{COMPONENT}}-main/catalogue.js"
    idempotent: yes

- name: Running uptime time 
  ansible.builtin.shell: set-hostname {{COMPONENT}}