filebeat.inputs:
- type: log
  id: log 
  enabled: true
{% if LOGTYPE == "json" %}
  json.keys_under_root: true 
{% endif %}
  paths:
    - "{{LOG_LOCATION}}"

  fields:
    level: "{{COMPONENT}}"
    logtype: {{LOGTYPE}}


setup.kibana:

output.logstash:
  hosts: ["172.31.74.164:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
