- name: Installing Java
  ansible.builtin.dnf:
    name: maven 
    state: installed 

- name: Creating {{APPUSER}} System Account
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes 

- name: Performing {{COMPONENT}} Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent 

- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Genetating Artifacts 
  ansible.builtin.shell : mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}/{{COMPONENT}}/

- name: Consiguring Systemd 
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{COMPONENT}}"
    enabled: yes
    # daemon_reload: true

- name: Configuring Server Name 
  ansible.builtin.shell: set-hostname {{COMPONENT}} 