# In ansible, if you attempt to print a variable that is not decalred, ANSIBLE throws an exception!
- name: Demo On Vars 
  hosts: all 
  vars:                          # Play level variables : if you declare a variable at play level, all tasks of the play can inherit them
    URL: play.google.com
  # gather_facts: false      
  tasks:
    - name: printing url
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      # in bash, we use "echo $URL"

    - name: printing url from task 
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      
      vars:                              # Task level variables : if you declare a variable at task level,only that task can use
        URL: task.google.com

    # - name: Printing city name
    #   ansible.builtin.debug:
    #     msg: "{{CITY}}"     

    - name: Printing OD Distro
      ansible.builtin.debug:
        msg: My OS Distro is {{ansible_distribution}} 

# Variable Precendece : cli variables > task variables > play variables

### When to use quotes and when not to use quotes in YAML while dealing with variables ?

###  ---> if in your print msg, if you just have varaible, then it's a must to enclose them in "" 's 
  