# In ansible, if you attempt to print a variable that is not decalred, ANSIBLE throws an exception!
- name: Demo On Vars 
  hosts: all 
  vars:                          # Play level variables : if you declare a variable at play level, all tasks of the play can inherit them
    URL: play.google.com
  tasks:
    - name: printing url
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      # in bash, we use "echo $URL"

    - name: printing url from task 
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      # in bash, we use "echo $URL"
      vars:                              # Task level variables : if you declare a variable at task level,only that task can use
        URL: task.google.com