- name: Demo on using shell Module  
  hosts: all 
  tasks: 
    - name: Running uptime time 
      ansible.builtin.shell: uptime  
      register: OUT

    - name: Pritning uptime time 
      ansible.builtin.debug:
        msg: "uptime is {{OUT}}"