- name: Demo on tasks 
  hosts: all 
  tasks:
    - name: Installing frontend
      ansible.builtin.debug:
        msg: Installing frontend

    - name: Starting frontend
      ansible.builtin.debug:
        msg: Starting frontend

    - name: Installing App
      ansible.builtin.debug:
        msg: Installing App

    - name: Starting App
      ansible.builtin.debug:
        msg: Starting App

    - name: Installing DB
      ansible.builtin.debug:
        msg: Installing DB

    - name: Starting DB
      ansible.builtin.debug:
        msg: Starting DB