- name: Demo on using shell Module  
  hosts: all 
  become: yes 
  tasks: 
    - name: Checking user
      ansible.builtin.shell: id       
      register: OUT                        

    - name: Printing user details
      ansible.builtin.debug:    
          msg: "userName is {{OUT.stdout}}" 
  
    - name: Creating roboshop useraccount
      ansible.builtin.user:
        name: robot