- name: Demo on using package 
  hosts: all 
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.package:
        name: nginx
        state: present

    # - name: Install the latest version of Apache and MariaDB
    #   ansible.builtin.package:
    #     name:
    #       - httpd
    #       - mariadb-server
    #     state: latest