- name: Copying the rsyslog config 
  ansible.builtin.template:
    src: syslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf

- name: Restart rsyslog  
  ansible.builtin.service:
    name: rsyslog   
    state: restarted
    enabled: true 
    daemon_reload: true 