- name: Disabling default {{COMPONENT}} repo
  ansible.builtin.shell: dnf module disable mysql -y 

- name: Copies {{COMPONENT}} repo file
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.dnf:
    name: mysql-community-server 
    state: installed 

- name: Starting {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: started
    name: mysqld
    enabled: yes

- name: Extracting {{COMPONENT}} password file 
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: psw_log

- name: Capturing the bash exit code 
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{psw_log.content|b64decode | regex_findall('.*temporary password.*')| join('') | split(' ')|last}}"

- name: Printing Def psw
  ansible.builtin.debug:
    msg: "{{DEFAULT_PASSWORD}}"

- name: Changing the default password 
  ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1'" | mysql  --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD}}"

- name: Uninstalling Password Validate Plugin
  ansible.builtin.shell: echo "uninstall plugin validate_password" | mysql -uroot -pRoboShop@1