- name: Enabling NodeJS18
  ansible.builtin.shell: dnf module disable nodejs -y ;  dnf module enable nodejs:18 -y

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs 
    state: installed 

- name: Creating {{APPUSER}} System Account
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes 

- name: Performing {{COMPONENT}} Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent 

- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Generating Artifacts
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring Server Name 
  ansible.builtin.shell: set-hostname {{COMPONENT}} 