- name: Enabling NodeJS18
  ansible.builtin.shell: dnf module disable nodejs -y ;  dnf module enable nodejs:18 -y

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs 
    state: installed 

- name: Creating {{APPUSER}} user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Downloading .pem file 
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /home/{{APPUSER}}/global-bundle.pem 
  become_user: "{{APPUSER}}"

## Uncomment this if you want to use the artifacts from Github
# - name: Dealing Artifacts
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_and_extract

# - name: Generating Artifacts
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Downloading Artifacts From Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

- name: Configuring Svc
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: configuring rsyslog
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Installing filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Installing node_exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter

- name: Set name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name